import { NextRequest, NextResponse } from 'next/server';

const whatsappPhoneId = process.env.WHATSAPP_PHONE_NUMBER_ID;
const whatsappToken = process.env.WHATSAPP_TOKEN;

if (!whatsappPhoneId || !whatsappToken) {
  console.error('WhatsApp credentials not configured');
}

type WhatsAppParams = {
  taskTitle: string;
  creatorPhoneNo: string;
  participant: string;
  response: string;
  aiRating: string;
  Reward: string;
  TaskBalance: string;
};

export async function POST(request: NextRequest) {
  try {
    if (!whatsappPhoneId || !whatsappToken) {
      return NextResponse.json(
        { error: 'WhatsApp credentials not configured' },
        { status: 500 }
      );
    }

    const params: WhatsAppParams = await request.json();

    const message = `🎯 *New Task Response Received*

📋 *Task:* ${params.taskTitle}
👤 *Participant:* ${params.participant}
⭐ *AI Rating:* ${params.aiRating}/10
💰 *Reward Paid:* ${params.Reward} cUSD
💳 *Task Balance:* ${params.TaskBalance} cUSD

📝 *Response:*
${params.response}

---
This response was automatically generated by EarnBase.`;

    const response = await fetch(
      `https://graph.facebook.com/v22.0/${whatsappPhoneId}/messages`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${whatsappToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messaging_product: 'whatsapp',
          to: params.creatorPhoneNo,
          type: 'text',
          text: {
            body: message,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorData = await response.json();
      console.error('WhatsApp API Error:', errorData);
      
      // Check for token expiry
      if (errorData.error?.code === 190) {
        return NextResponse.json(
          { 
            error: 'WhatsApp access token has expired. Please update your WHATSAPP_TOKEN environment variable.',
            code: 'TOKEN_EXPIRED'
          },
          { status: 401 }
        );
      }
      
      return NextResponse.json(
        { error: `WhatsApp API error: ${errorData.error?.message || 'Unknown error'}` },
        { status: 500 }
      );
    }

    const result = await response.json();
    console.log('WhatsApp message sent successfully:', result);
    
    return NextResponse.json({ success: true, data: result });
  } catch (error) {
    console.error('Error sending WhatsApp message:', error);
    return NextResponse.json(
      { error: 'Failed to send WhatsApp message' },
      { status: 500 }
    );
  }
}
