import { NextRequest, NextResponse } from 'next/server';
import { sendEmail } from '@/lib/SendEmail';

type EmailParams = {
  taskTitle: string;
  creatorEmail: string;
  participant: string;
  response: string;
  aiRating: string;
  Reward: string;
  TaskBalance: string;
};

export async function POST(request: NextRequest) {
  try {
    const params: EmailParams = await request.json();

    // Create a formatted email message
    const subject = `🎯 New Task Response: ${params.taskTitle}`;
    
    const htmlBody = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 24px; border: 1px solid #ddd; border-radius: 10px; background-color: #f9f9f9;">
        <h2 style="color: #2c3e50; font-size: 24px;">🎯 New Task Response Received</h2>
        
        <div style="background-color: #fff; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #4CAF50;">
          <h3 style="color: #333; margin-top: 0;">Task Details</h3>
          <p style="margin: 8px 0;"><strong>Task:</strong> ${params.taskTitle}</p>
          <p style="margin: 8px 0;"><strong>Participant:</strong> ${params.participant}</p>
          <p style="margin: 8px 0;"><strong>AI Rating:</strong> ${params.aiRating}/10</p>
          <p style="margin: 8px 0;"><strong>Reward Paid:</strong> ${params.Reward} cUSD</p>
          <p style="margin: 8px 0;"><strong>Task Balance:</strong> ${params.TaskBalance} cUSD</p>
        </div>

        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="color: #333; margin-top: 0;">Response Content</h3>
          <div style="background-color: #fff; padding: 15px; border-radius: 6px; border: 1px solid #e9ecef;">
            <p style="margin: 0; white-space: pre-wrap; line-height: 1.6;">${params.response}</p>
          </div>
        </div>

        <div style="text-align: center; margin: 30px 0; padding: 20px; background-color: #e3f2fd; border-radius: 8px;">
          <p style="margin: 0; color: #1976d2; font-weight: bold;">
            This response was automatically generated by EarnBase
          </p>
        </div>

        <div style="border-top: 1px solid #ddd; padding-top: 20px; margin-top: 30px; text-align: center; color: #666; font-size: 12px;">
          <p>Thank you for using EarnBase - Connecting creators with participants through blockchain technology</p>
        </div>
      </div>
    `;

    const textBody = `
New Task Response Received

Task: ${params.taskTitle}
Participant: ${params.participant}
AI Rating: ${params.aiRating}/10
Reward Paid: ${params.Reward} cUSD
Task Balance: ${params.TaskBalance} cUSD

Response:
${params.response}

---
This response was automatically generated by EarnBase.
    `;

    // Send email using the existing sendEmail function
    const result = await sendEmail(params.creatorEmail, subject, htmlBody, textBody);
    
    console.log('Email sent successfully:', result);
    
    return NextResponse.json({ success: true, data: result });
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email notification' },
      { status: 500 }
    );
  }
}
